---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
There was an ancient City, stricken down    
With a strange frenzy, and for many a day     
They paced from morn to eve the crowded town,    
And danced the night away.     
  
I asked the cause: the aged man grew sad: 
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
A governor it was proclaimed this time,     
When all who would come seeking in New Hampshire    
Ancestral memories might come together.     
And those of the name Stark gathered in Bow,    
A rock-strewn town where farming has fallen off  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining with all his might:    
He did his very best to make    
      The billows smooth and bright —    
And this was odd, because it was    
      The middle of the night.    
  
The moon was shining sulkily,    
      Because she thought the sun    
Had got no business to be there    
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Curtains forcing their will        
against the wind,        
children sleep,        
exchanging dreams with        
seraphim. The city        
drags itself awake on        
subway straps; and        
I, an alarm, awake as a        
rumor of war      
lie stretching into dawn        
unasked and unheeded.  
  